name: CD (Publish to npm)

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write # for npm provenance (requires Node 18+ and npm >=9)

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Bump version & decide publish flags
        id: pkg
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          NEW_VER=$(npm version patch -m "chore: release v%s [skip ci]")
          echo "New version: $NEW_VER"
          git push --follow-tags

          # Expose tag (vX.Y.Z) and version (X.Y.Z) for later steps
          VER_NO_V=${NEW_VER#v}
          echo "tag=$NEW_VER" >> "$GITHUB_OUTPUT"
          echo "version=$VER_NO_V" >> "$GITHUB_OUTPUT"

          NAME=$(node -p "require('./package.json').name")
          echo "name=$NAME" >> "$GITHUB_OUTPUT"
          if npm view "$NAME" version >/dev/null 2>&1; then
            echo "flags=" >> "$GITHUB_OUTPUT"
          else
            echo "flags=--access public" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release from tag (first-party)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          TAG="${{ steps.pkg.outputs.tag }}"
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG already exists; skipping creation."
          else
            gh release create "$TAG" \
              --title "Release $TAG" \
              --generate-notes \
              --latest
          fi

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish ${{ steps.pkg.outputs.flags }} --provenance
